Improved GitHub Actions
engineerjoe440/ElectricPy pull request #26
Opened 2021-11-11 06:56 UTC by Lakshmikanth2001

As in my previous commit #23, I have added a feature that will automatically install dependencies during `pip install electricPy `,

keeping this in mind I have removed steps in GitHub actions that used to manually install dependencies during `CI and CD`

2021-11-13 00:51 UTC, engineerjoe440 requested changes
This seems reasonable, though I'm not a fan of commented-out code. Let's just remove the lines altogether!

2021-11-13 09:55 UTC, Lakshmikanth2001 commented
Done !!!

2021-11-16 05:09 UTC, engineerjoe440 commented
Excellent! Thank you!!!!

2021-11-16 05:10 UTC, engineerjoe440 approved these changes

2021-11-16 05:13 UTC, merged