`Black` Code Formatting & Improving GitHub Actions
engineerjoe440/ElectricPy pull request #45
Opened 2022-02-24 15:27 UTC by Lakshmikanth2001

please review this pull request and give your valuable feed back

2022-03-08 04:26 UTC, engineerjoe440 requested changes
Wow!
That was much less painful than I'd expected. Well done! I think we'll still want to touch up a few things, and see if we can't make some of the function defenitions a little easier to interpret.

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/__init__.py
> +                "Invalid Earth Resistivity string try to select \
- [ ] change:

```python
"Invalid Earth Resistivity string try to select \
from set of (SEA, SWAMP, AVG, AVERAGE, DAMP, DRY, SAND, SANDSTONE"
```

to

```python
"Invalid Earth Resistivity string try to select "
"from set of (SEA, SWAMP, AVG, AVERAGE, DAMP, DRY, SAND, SANDSTONE"
```

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/__init__.py
> +    Vin_min: float Minimum input voltage in (volts)
- [ ] visually align columns
- [ ] type should be on one line, description should be on following line

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/constants.py
> +    / 3
- [ ] there must be a way to clean this up a bit. It's visually disruptive to read (thus difficult to maintain)

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/constants.py
> +    / 3
- [ ] there must be another way to clean this up and make it more visually cohesive so it'll be easier to maintain.

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/constants.py
> +    / 3
- [ ] as above, there's got to be a way to clean this up

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/phasor.py
> +                hand = _plt.arrow(
- [ ] as with other places, this seems a little unnatural. Perhaps we could use the keywords for the variables, or reduce it to a single row of arguments?

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/visu.py
> +                    self.radius,
- [ ] This is clunky, there must be another way to clean it up so that it's better to understand visually.

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/sim.py
> +    A,
still not sure about how this breaks down visually... hmm....

2022-03-08 04:26 UTC, engineerjoe440 commented on electricpy/fault.py
> +    k2 *= _np.sqrt(
- [ ] let's see if we can clean this formula up a bit, it seems messy and all over the place with this visual breakdown (though, admittedly, it wasn't much better before)

2022-03-14 03:00 UTC, Lakshmikanth2001 commented
Sir any updates ?

2022-03-24 22:42 UTC, engineerjoe440 requested changes
Sorry I'm not getting any better about responding in a timely fashion. This work is looking terrific! I'm impressed that Black hasn't made a bigger mess. I think much of that is thanks to you, so well done!

2022-03-24 22:42 UTC, engineerjoe440 commented on electricpy/__init__.py
> +            "An Error Was Encountered.\n" "Not enough arguments were provided."
could still be simplified to:

```python
print(
            "An Error Was Encountered.\nNot enough arguments were provided."
)
```

2022-03-24 22:42 UTC, engineerjoe440 commented on electricpy/__init__.py
> +    Vin_min: float Minimum input voltage in (volts)
# Alignment example:

```
Vin_min:      float
              Minimum input voltage in (volts)
Vin_max:      float
              Maximum input voltage in (volts)
Vout:         float
              Output voltage in (volts)
load_current: float 
              Load current in (amps)
```

and

```
R:          float
            Resitance of the zener diode
P_zener:    float
            Power of the zener diode
P_resistor: float
            Power of the resistor
```

This gives us visual appeal in the source code itself, and doesn't affect the Sphinx documentation negatively. It allows us to keep more consistent, appealing documentation directly in the code :)

2022-03-24 22:42 UTC, engineerjoe440 commented on electricpy/phasor.py
> +                hand = _plt.arrow(
could just use `x, y` and `dx, dy`: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.arrow.html

2022-03-24 22:42 UTC, engineerjoe440 commented on electricpy/sim.py
> +    A,
I'm not gonna fight this one. LGTM.

2022-03-24 22:42 UTC, engineerjoe440 commented on electricpy/visu.py
> +                    self.radius,
Can we do:

```python
self.radius, self.center, self.operating_point = PowerCircle._build_circle(
...
```

?

2022-03-24 22:42 UTC, engineerjoe440 commented on electricpy/fault.py
> +    k2 *= _np.sqrt(
not gonna fight this one.... LGTM (Looks good to me)

2022-05-06 17:36 UTC, closed without merging