bug fix for tcycle method
engineerjoe440/ElectricPy pull request #93
Opened 2022-06-13 11:25 UTC by Lakshmikanth2001

- removed leading spaces
- added test function for `tcycle`
- improved `tcycle` method

2022-07-01 08:45 UTC, Lakshmikanth2001 commented
any updates please

2022-07-01 22:18 UTC, engineerjoe440 commented
> any updates please

Thank you for the reminder! This fell off my "to-do list".

2022-07-01 22:19 UTC, engineerjoe440 requested changes
Only one comment about reducing the number of lines for the assertion-check in `__init__.py`

With that, we should be good to merge!

2022-07-01 22:19 UTC, engineerjoe440 commented on electricpy/__init__.py
> +    try:
this could be condensed to the following:

```python
if 0 not in freq:
    raise ZeroDivisionError("Frequency must not be 0")
```

2022-07-01 22:19 UTC, engineerjoe440 commented on test/test_electricpy.py
> +    with pytest.raises(ZeroDivisionError):
LOVE this!

2022-07-02 09:46 UTC, Lakshmikanth2001 commented on test/test_electricpy.py
> +    with pytest.raises(ZeroDivisionError):
Thank You 😊😊

2022-07-02 17:09 UTC, engineerjoe440 approved these changes
Looks great!!! Thank you!

2022-07-02 17:10 UTC, merged