Improve Test Organization
engineerjoe440/ElectricPy pull request #95
Opened 2022-06-25 05:56 UTC by Lakshmikanth2001

- omitted the use of `exec` in all test cases
- Improve test grouping

2022-07-01 08:45 UTC, Lakshmikanth2001 commented
Any updates please

2022-07-01 22:23 UTC, engineerjoe440 requested changes
Just some little documentation stuff. Looks great! Thank you!

2022-07-01 22:23 UTC, engineerjoe440 commented on electricpy/__init__.py
> +                Boolean control to enable return in rpm. default
Please complete the `default=False` statement.

2022-07-02 17:08 UTC, engineerjoe440 approved these changes
Fantastic!!!! Thank you!

2022-07-02 17:08 UTC, merged